# Generated by Django 3.0.4 on 2020-05-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20200517_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='url',
        ),
        migrations.AlterField(
            model_name='listing',
            name='Title',
            field=models.TextField(max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_locality',
            field=models.CharField(max_length=20),
        ),
    ]
